### ISSUE TITLE
Support for (basic) http authentication

### ISSUE THREAD

**Issue by evetion** [ioos/thredds_crawler#11]
Adding optional username and password options to the init of the Crawl class would enable harvesting of password protected thredds catalogs.

It is then easily passed on to the requests module, which support basic authentication out of the box: 
`r = requests.get(url)` becomes `r = requests.get(url,auth=('user', 'pass'))`
See also the [requests documentation](http://docs.python-requests.org/en/latest/user/authentication/):

**Comment by kwilcox** [comment]
@evetion if you are still interested, can you test this fork with a password protected TDS server? https://github.com/kwilcox/thredds_crawler
