### ISSUE TITLE
OOI TDS stall

### ISSUE THREAD

**Issue by cedwards2** [ioos/thredds_crawler#20]
Hi.  I've just begun using this.  It is an amazing tool.  Thank you for sharing it.  It seems to work very well for a few TDS that I have tried, but seems to completely stall on the OOI TDS.

For example, running:
url = 'http://opendap.oceanobservatories.org:8090/thredds/catalog/ooi-preliminary-datasets/Coastal_Endurance/CE05MOAS/05-CTDGVM000/recovered_host/catalog.html'
c = Crawl(url)

never returns to a prompt.  I have no idea how to find out what it is about the OOI TDS that causes this, but I thought I'd post it here in case you knew what the issue might be and how to resolve.

Chris

**Comment by kwilcox** [comment]
@cedwards2 Seems fixed? https://gist.github.com/kwilcox/8fde7fb74d3a5189530e8b941263f840

**Comment by kwilcox** [comment]
Closing per https://gist.github.com/kwilcox/8fde7fb74d3a5189530e8b941263f840#gistcomment-1889166
