### ISSUE TITLE
Please change license from GPL-3.0 to MIT so that Unidata can use 

### ISSUE THREAD

**Issue by rsignell-usgs** [ioos/thredds_crawler#21]
Could the license be changed here from GPL-3.0 to MIT?
Unidata is interested in crawling catalogs as [discussed here](https://github.com/Unidata/thredds/issues/648#issuecomment-249926376) but the GPL-3.0 license is [a problem for them](https://github.com/Unidata/thredds/issues/648#issuecomment-249926376)

**Comment by ocefpaf** [comment]
Better yet BSD 3-Clause. (See https://github.com/github/choosealicense.com/issues/413#issuecomment-243598510)

**Comment by rsignell-usgs** [comment]
I'll leave that up to RPS-ASA.   I'm pretty sure Unidata would be happy with either, right @dopplershift?

**Comment by lukecampbell** [comment]
release 1.5.1 of thredds_crawler is licensed under MIT. All previous licenses are still GPLv3, so as long as your using greater than 1.5.1, it's all good.

**Comment by lukecampbell** [comment]
and it's under ioos.

**Comment by lukecampbell** [comment]
@ocefpaf The BSD-3 Clause is virtually identical to the MIT license except it has provisions of non-endorsement by the copyright holder. I didn't see this issue until after I made the change to MIT, but I don't think we need the non-endorsement clause. The goal I had when choosing a license was to get as close to public domain as possible while retaining limited liability and promoting open source collaboration.

I will say this though. It's incongruous that BSD-3 was omitted from the listing of open source licenses in that discussion you posted.

**Comment by ocefpaf** [comment]
I get the similarities and here it is not a big issue. But lately I am choosing BSD over MIT mostly b/c of this part in the thread:

> Therefore, the MIT license allows for the copying and redistribution of some of the work of art without attribution. As an academic, I consider copying without attribution plagiarism. BSD licenses require attribution. BSD provides a legal framework for pursuing plagiarism infringements in a way that the MIT license does not.

**Comment by lukecampbell** [comment]
Ah, you're right, I didn't notice that BSD had an attribution clause that MIT didn't.
